#!/usr/bin/env python3
"""
Emit paper/appendix_tables.tex from the result files, so the appendix numbers are
generated rather than retyped. Rerun after any experiment changes.

Usage:  python -X utf8 analysis/make_appendix_tables.py
"""
import io
import os

import pandas as pd

R = "analysis/results"
OUT = "paper/appendix_tables.tex"


def tex_escape(s):
    return str(s).replace("_", r"\_")


def table(df, caption, label, cols, headers, fmt=None, small=True, tight=False):
    fmt = fmt or {}
    align = "l" + "c" * (len(cols) - 1)
    out = ["\\begin{table}[tb]", "\\centering",
           "\\caption{%s}" % caption, "\\label{%s}" % label]
    if tight:                 # 12 columns do not fit a 6.5in line at \small
        out.append("\\footnotesize")
        out.append("\\setlength{\\tabcolsep}{3pt}")
    elif small:
        out.append("\\small")
    out += ["\\begin{tabular}{%s}" % align, "\\toprule",
            " & ".join(headers) + " \\\\", "\\midrule"]
    for _, r in df.iterrows():
        cells = []
        for c in cols:
            v = r[c]
            if c in fmt:
                cells.append(fmt[c](v))
            elif isinstance(v, float):
                cells.append("%.3f" % v)
            else:
                cells.append(tex_escape(v))
        out.append(" & ".join(cells) + " \\\\")
    out += ["\\bottomrule", "\\end{tabular}", "\\end{table}", ""]
    return "\n".join(out)


def main():
    parts = []

    # --- A: the published split, per tissue ------------------------------
    a = pd.read_csv(f"{R}/eqtl_leakage.tsv", sep="\t")
    a["ci"] = a.apply(lambda r: "[%.2f, %.2f]" % (r.dist_ci_lo, r.dist_ci_hi), axis=1)
    a["gene_in_train"] = (a.test_gene_in_train * 100).round(0).astype(int).astype(str) + "\\%"
    a["locus_in_train"] = (a.test_locus_in_train * 100).round(0).astype(int).astype(str) + "\\%"
    parts.append(table(
        a, "Published eQTLP test split, per tissue. \\textbf{dist} is our "
        "zero-training distance baseline scored from the released coordinates, with "
        "a 95\\% bootstrap CI; \\textbf{expert}, \\textbf{hyena} and \\textbf{cad-ph} "
        "are the published numbers. Every test gene appears in training.",
        "tab:a1",
        ["tissue", "test_pos", "test_neg", "pos_train", "pos_test", "auroc_distance",
         "ci", "pub_expert", "pub_hyena", "pub_cad_ph", "gene_in_train", "locus_in_train"],
        ["Tissue", "pos", "neg", "$p$ train", "$p$ test", "dist", "95\\% CI",
         "expert", "hyena", "cad-ph", "gene", "locus"],
        fmt={"test_pos": lambda v: str(int(v)), "test_neg": lambda v: str(int(v)),
             "pos_train": lambda v: "%.2f" % v, "pos_test": lambda v: "%.2f" % v,
             "ci": str, "gene_in_train": str, "locus_in_train": str}, tight=True))

    # --- body: the same per-tissue evidence, trimmed to the argument -----
    body = table(
        a, "Published eQTLP test split, per tissue. \\textbf{dist} is our "
        "zero-training baseline, scored from the released coordinates, with a 95\\% "
        "bootstrap CI; \\textbf{expert} (Enformer), \\textbf{hyena} and "
        "\\textbf{cad-ph} are the benchmark's published numbers. Distance wins in "
        "every tissue, the CIs are 0.10--0.19 wide, and every test gene appears in "
        "training. Full columns in Appendix~A.",
        "tab:tissues",
        ["tissue", "test_pos", "test_neg", "auroc_distance", "ci",
         "pub_expert", "pub_hyena", "pub_cad_ph", "gene_in_train"],
        ["Tissue", "$n_+$", "$n_-$", "dist", "95\\% CI", "expert", "hyena",
         "cad-ph", "gene in train"],
        fmt={"test_pos": lambda v: str(int(v)), "test_neg": lambda v: str(int(v)),
             "ci": str, "gene_in_train": str}, tight=True)
    io.open("paper/body_table_tissues.tex", "w", encoding="utf-8").write(
        "% generated by analysis/make_appendix_tables.py -- do not edit by hand\n" + body)
    print("wrote paper/body_table_tissues.tex (1 table)")

    # --- B: the eQTLP-v2 baseline grid -----------------------------------
    b = pd.read_csv(f"{R}/eqtl_v2_baselines.tsv", sep="\t")
    b = b[["version", "scheme", "model", "auroc", "fold_mean", "fold_sd", "n", "n_pos"]]
    parts.append(table(
        b, "eQTLP-v2 baseline grid. \\textbf{all} is every pooled pair; "
        "\\textbf{matched} is the distance-matched subset the paper uses. "
        "\\textbf{random} allows locus memorisation; \\textbf{gene} and "
        "\\textbf{chrom} do not.",
        "tab:b1",
        ["version", "scheme", "model", "auroc", "fold_mean", "fold_sd", "n", "n_pos"],
        ["Version", "Split", "Model", "AUROC", "fold mean", "fold SD", "$n$", "$n_+$"],
        fmt={"n": lambda v: "%d" % v, "n_pos": lambda v: "%d" % v,
             "fold_sd": lambda v: "%.3f" % v}))

    # --- body: what each split scheme lets a feature exploit -------------
    piv = b.pivot_table(index="model", columns=["version", "scheme"], values="auroc")
    order = ["distance", "gene_prior", "dist+mask_count", "composition",
             "dist+comp", "dist+comp+allele"]
    rows = []
    for m in order:
        if m not in piv.index:
            continue
        rows.append({"model": m,
                     "a_rand": piv.loc[m, ("all", "random")],
                     "a_chrom": piv.loc[m, ("all", "chrom")],
                     "m_rand": piv.loc[m, ("matched", "random")],
                     "m_chrom": piv.loc[m, ("matched", "chrom")]})
    sh = pd.DataFrame(rows)
    sh["model"] = sh["model"].map({
        "distance": "distance to TSS", "gene_prior": "gene's train positive rate",
        "dist+mask_count": "distance + label-mask count",
        "composition": "local composition", "dist+comp": "distance + composition",
        "dist+comp+allele": "distance + composition + allele"})
    shim = table(
        sh, "What each split lets a simple feature exploit, on eQTLP-v2. "
        "\\textbf{all} keeps the original distance imbalance, \\textbf{matched} "
        "removes it; \\textbf{random} lets genes recur across the split, "
        "\\textbf{chrom} does not. Distance falls 0.79$\\to$0.50 under matching, and "
        "the gene prior falls 0.70$\\to$0.44 under chromosome holdout: those two "
        "columns are the shortcuts. The label-mask count collapses from 0.78 to "
        "0.44, confirming it is a label leak. Composition on matched/chrom is the "
        "floor; the 0.599 in the text is its mean over 7 matchings $\\times$ 10 "
        "partitions, while this cell is the single seed-0 matching.",
        "tab:shortcuts",
        ["model", "a_rand", "a_chrom", "m_rand", "m_chrom"],
        ["Feature", "all / random", "all / chrom", "matched / random",
         "matched / chrom"])
    io.open("paper/body_table_shortcuts.tex", "w", encoding="utf-8").write(
        "% generated by analysis/make_appendix_tables.py -- do not edit by hand\n" + shim)
    print("wrote paper/body_table_shortcuts.tex (1 table)")

    # --- body + appendix: the end-to-end fine-tuning run -----------------
    import glob
    import json
    ft = []
    for path in sorted(glob.glob(f"{R}/finetune/fold*_len131072.json")):
        d = json.load(open(path))
        fold = int(d["args"]["fold"])
        for h in d["history"]:
            ft.append({"fold": fold, "epoch": h["epoch"], "refalt": h["refalt"],
                       "ref_copy": h["ref_copy"], "delta": h["delta"],
                       "loss": h["train_loss"], "n": h["n"],
                       "hours": h["epoch_sec"] / 3600})
    if ft:
        f_df = pd.DataFrame(ft).sort_values(["fold", "epoch"])
        cap = ("End-to-end fine-tuning of HyenaDNA-medium-450k on eQTLP-v2, through "
               "the benchmark's own readout. Training works --- loss falls and "
               "\\texttt{refalt} rises on 2 of 3 folds --- and lands at the frozen "
               "probe's accuracy, but the allele gap never leaves the fourth decimal.")
        # NOT appended to `parts`: this one lives in the body, and adding it there
        # would shift the index slices that split `parts` into appendix sections
        ft_tab = table(
            f_df, cap, "tab:ft",
            ["fold", "epoch", "refalt", "ref_copy", "delta", "loss", "n", "hours"],
            ["Fold", "Epoch", "\\texttt{refalt}", "\\texttt{ref\\_copy}", "$\\Delta$",
             "train loss", "$n$", "h"],
            fmt={"fold": lambda v: "%d" % v, "epoch": lambda v: "%d" % v,
                 "refalt": lambda v: "%.4f" % v, "ref_copy": lambda v: "%.4f" % v,
                 "delta": lambda v: "%+.5f" % v, "loss": lambda v: "%.4f" % v,
                 "n": lambda v: "%d" % v, "hours": lambda v: "%.1f" % v})
        io.open("paper/body_table_finetune.tex", "w", encoding="utf-8").write(
            "% generated by analysis/make_appendix_tables.py -- do not edit by hand\n"
            + ft_tab)
        print("wrote paper/body_table_finetune.tex (1 table)")

    # --- C: per-fold ablation and the probe-strength sweep ---------------
    c = pd.read_csv(f"{R}/robustness/F1_per_fold.tsv", sep="\t")
    c = c.sort_values(["model", "fold", "seed"])
    parts.append(table(
        c, "Per-fold test AUROC behind Figure 1a, and the \\texttt{ref\\_copy} "
        "ablation on the identical fitted model. The CNN contributes 3 seeds per fold.",
        "tab:c1",
        ["model", "fold", "seed", "refalt", "ref_copy"],
        ["Model", "Fold", "Seed", "\\texttt{refalt}", "\\texttt{ref\\_copy}"],
        fmt={"fold": lambda v: "%d" % v, "seed": lambda v: "%d" % v,
             "refalt": lambda v: "%.4f" % v,
             "ref_copy": lambda v: "--" if pd.isna(v) else "%.4f" % v}))

    d = pd.read_csv(f"{R}/robustness/R4_probes.tsv", sep="\t")
    d = d[d.scheme == "chrom_fixed"][["model", "C", "refalt", "ref_copy",
                                      "diff_only_logit", "floor", "delta"]]
    parts.append(table(
        d, "Probe-strength sweep on the fixed chromosome folds. The "
        "\\texttt{refalt}--\\texttt{ref\\_copy} gap stays at the fourth decimal at "
        "every regularisation strength, and every probe sits below the floor.",
        "tab:c2",
        ["model", "C", "refalt", "ref_copy", "diff_only_logit", "floor", "delta"],
        ["Model", "$C$", "\\texttt{refalt}", "\\texttt{ref\\_copy}",
         "\\texttt{diff\\_only}", "floor", "$\\Delta$"],
        fmt={"C": lambda v: "%g" % v, "refalt": lambda v: "%.4f" % v,
             "ref_copy": lambda v: "%.4f" % v,
             "diff_only_logit": lambda v: "%.4f" % v,
             "delta": lambda v: "%+.5f" % v}))

    # --- D: the CNN, per fold and seed -----------------------------------
    e = pd.read_csv(f"{R}/robustness/R8_cnn_seeds.tsv", sep="\t")
    parts.append(table(
        e, "End-to-end CNN on eQTLP-v2, 5 folds $\\times$ 3 seeds. \\textbf{alt} is "
        "the real pair, \\textbf{ref\\_copy} replaces the alternate allele with the "
        "reference, and \\textbf{rand} substitutes a base that never occurred.",
        "tab:d1",
        ["fold", "seed", "alt", "ref_copy", "rand", "d_copy"],
        ["Fold", "Seed", "alt", "\\texttt{ref\\_copy}", "rand", "$\\Delta$"],
        fmt={"fold": lambda v: "%d" % v, "seed": lambda v: "%d" % v,
             "alt": lambda v: "%.4f" % v, "ref_copy": lambda v: "%.4f" % v,
             "rand": lambda v: "%.4f" % v, "d_copy": lambda v: "%+.5f" % v}))

    # --- F: clinical set, gene-concentration check -----------------------
    f = pd.read_csv(f"{R}/robustness/R9_clinical_gene_influence.tsv", sep="\t")
    f = f.rename(columns={f.columns[0]: "row"})
    parts.append(table(
        f, "Clinical set, sensitivity to gene concentration. Dropping the most "
        "frequent genes, or keeping one pair per gene, leaves every score at chance.",
        "tab:f1",
        list(f.columns),
        ["Quantity"] + [tex_escape(c) for c in f.columns[1:]],
        fmt={c: (lambda v: "--" if pd.isna(v) else ("%g" % v if isinstance(v, float) else tex_escape(v)))
             for c in f.columns}))

    # one file per appendix section, in the order appendix.tex inputs them
    groups = {"a": parts[0:1], "b": parts[1:2], "c": parts[2:4],
              "d": parts[4:5], "f": parts[5:6]}
    os.makedirs("paper", exist_ok=True)
    for letter, chunk in groups.items():
        path = f"paper/appendix_tables_{letter}.tex"
        io.open(path, "w", encoding="utf-8").write(
            "% generated by analysis/make_appendix_tables.py -- do not edit by hand\n"
            + "\n".join(chunk))
        print(f"wrote {path} ({len(chunk)} table{'s' if len(chunk) > 1 else ''})")


if __name__ == "__main__":
    main()
